use DLithe;


--=====================================================
CREATE TABLE CONSTRAINT_DEMO
(
ID INT,
NAME VARCHAR(25) NOT NULL,
AGE INT CHECK(AGE>18),             --COLOUMN LEVEL
ADDRESS VARCHAR(25) DEFAULT 'BANGALORE',
CONSTRAINT PK_ID PRIMARY KEY(ID)
);


--===========================================

CREATE TABLE CONSTRAINT_DEMO2
(
ID INT,
NAME VARCHAR(25) NOT NULL,
AGE INT,
ADDRESS VARCHAR(25) DEFAULT 'BANGALORE',
CONSTRAINT PK_ID2 PRIMARY KEY(ID),   --TABLE LEVEL
CONSTRAINT CK_AGE CHECK(AGE>18)
);


--===============================================
--INSERTING MULTIPLE VALUES

INSERT INTO CONSTRAINT_DEMO2 VALUES
(1,'AAA',22,'BBB'),
(2,'BBB',23,'CCC'),
(3,'CCC',24,'DDD'),
(4,'DDD',22,'AAA');


SELECT * FROM CONSTRAINT_DEMO2;